name: easypharma_flutter
description: "Application EasyPharma - Commande de m√©dicaments."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  google_fonts: ^6.3.2
  http: ^1.6.0
  flutter_launcher_icons: ^0.14.4
  location: ^8.0.1
  device_info_plus: ^12.3.0
  app_settings: ^6.0.0
  dio: ^5.3.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  url_launcher: ^6.2.1
  # uni_links removed: using local platform channels in MainActivity instead
  image_picker: ^1.0.4
  geocoding: ^3.0.0
  path: ^1.8.3
  http_parser: ^4.0.0
  permission_handler: ^12.0.1

dev_dependencies:
  build_runner: ^2.5.2
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
